local gui = require "gui"

_ENV = module(...)

gui.ITEM_NONE=gui.itemNone()
gui.npos=-1

gui.None = -1
gui.MouseButtonLeft = 0
gui.MouseButtonRight = 1
gui.MouseButtonMiddle = 2
gui.Button0 = 0
gui.Button1 = 1
gui.Button2 = 2
gui.Button3 = 3
gui.Button4 = 4
gui.Button5 = 5
gui.Button6 = 6
gui.Button7 = 7

gui.key=
{
	None=0,
	Escape=1,
	One=2,
	Two=3,
	Three=4,
	Four=5,
	Five=6,
	Six=7,
	Seven=8,
	Eight=9,
	Nine=10,
	Zero=11,
	Minus=12, --  - on main keyboard
	Equals=13,
	Backspace=14, --Backspace
	Tab=15,
	Q=16,
	W=17,
	E=18,
	R=19,
	T=20,
	Y=21,
	U=22,
	I=23,
	O=24,
	P=25,
	LeftBracket=26,
	RightBracket=27,
	Return=28, --Enter on main keyboard
	LeftControl=29,
	A=30,
	S=31,
	D=32,
	F=33,
	G=34,
	H=35,
	J=36,
	K=37,
	L=38,
	Semicolon=39,
	Apostrophe=40,
	Grave=41, -- Accent grave ( ~ )
	LeftShift=42,
	Backslash=43,
	Z=44,
	X=45,
	C=46,
	V=47,
	B=48,
	N=49,
	M=50,
	Comma=51,
	Period=52, -- . on main keyboard
	Slash=53, -- '/' on main keyboard
	RightShift=54,
	Multiply=55, -- * on numeric keypad
	LeftAlt=56,
	Space=57,
	Capital=58,
	F1=59,
	F2=60,
	F3=61,
	F4=62,
	F5=63,
	F6=64,
	F7=65,
	F8=66,
	F9=67,
	F10=68,
	NumLock=69,
	ScrollLock=70, -- Scroll Lock
	Numpad7=71,
	Numpad8=72,
	Numpad9=73,
	Subtract=74, -- on numeric keypad
	Numpad4=75,
	Numpad5=76,
	Numpad6=77,
	Add=78, -- + on numeric keypad
	Numpad1=79,
	Numpad2=80,
	Numpad3=81,
	Numpad0=82,
	Decimal=83,
	OEM_102=86, --< > | on UK/Germany keyboards
	F11=87, 
	F12=88,
	F13=89, -- (NEC PC98)
	F14=90,
	F15=91,
	Kana=112, -- Japanese keyboard
	ABNT_C1=115, -- on Portugese (Brazilian) keyboards
	
	Convert         = 0x79,    -- (Japanese keyboard) 
	NoConvert       = 0x7B,    -- (Japanese keyboard)
	Yen             = 0x7D,    -- (Japanese keyboard) 
	ABNT_C2         = 0x7E,    -- Numpad . on Portugese (Brazilian) keyboards
	NumpadEquals    = 0x8D,    -- = on numeric keypad (NEC PC98)
	PrevTrack       = 0x90,    -- Previous Track (KC_CIRCUMFLEX on Japanese keyboard)
	At              = 0x91,    --                     (NEC PC98)
	Colon           = 0x92,    --                     (NEC PC98)
	Underline       = 0x93,    --                     (NEC PC98)
	Kanji           = 0x94,    -- (Japanese keyboard)
	Stop            = 0x95,    --                     (NEC PC98)
	AX              = 0x96,    --                     (Japan AX)
	Unlabeled       = 0x97,    --                        (J3100)
	NextTrack       = 0x99,    -- Next Track
	NumpadEnter     = 0x9C,    -- Enter on numeric keypad
	RightControl    = 0x9D,
	Mute            = 0xA0,
	Calculator      = 0xA1,
	PlayPause       = 0xA2,    -- Play / Pause 
	MediaStop       = 0xA4,    -- Media Stop 
	VolumeDown      = 0xAE,    -- Volume -
	VolumeUp        = 0xB0,    -- Volume + 
	WebHome         = 0xB2,    -- Web home 
	NumpadComma     = 0xB3,    -- , on numeric keypad (NEC PC98) 
	Divide          = 0xB5,    -- / on numeric keypad 
	SysRq           = 0xB7,
	RightAlt        = 0xB8,    -- Right Alt
	Pause           = 0xC5,
	Home            = 0xC7,    -- Home on arrow keypad 
	ArrowUp         = 0xC8,    -- UpArrow on arrow keypad 
	PageUp          = 0xC9,    -- PgUp on arrow keypad 
	ArrowLeft       = 0xCB,    -- LeftArrow on arrow keypad 
	ArrowRight      = 0xCD,    -- RightArrow on arrow keypad 
	End             = 0xCF,    -- End on arrow keypad 
	ArrowDown       = 0xD0,    -- DownArrow on arrow keypad
	PageDown		= 0xD1,    -- PgDn on arrow keypad
	Insert          = 0xD2,    -- Insert on arrow keypad 
	Delete          = 0xD3,    -- Delete on arrow keypad 
	LeftWindows     = 0xDB,    -- Left Windows key 
	RightWindow     = 0xDC,    -- Right Windows key
	RightWindows    = 0xDC,    -- Right Windows key - Correct spelling :)
	AppMenu         = 0xDD,    -- AppMenu key 
	Power           = 0xDE,    -- System Power 
	Sleep           = 0xDF,   -- System Sleep 
	Wake			= 0xE3,    -- System Wake
	WebSearch		= 0xE5,
	WebFavorites	= 0xE6,
	WebRefresh		= 0xE7,
	WebStop			= 0xE8,
	WebForward		= 0xE9,
	WebBack			= 0xEA,
	MyComputer		= 0xEB,
	Mail			= 0xEC,
	MediaSelect		= 0xED	
}
